import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
import os
from sklearn.preprocessing import MinMaxScaler

load_dotenv()

GMAIL = os.getenv("GMAIL_ADDRESS")
PASSWORD = os.getenv("GMAIL_APP_PASSWORD")

def get_top_restaurants(top_n=5):
    df = pd.read_csv("restaurants.csv")
    df["price_level"] = df["price_level"].replace({
        "PRICE_LEVEL_INEXPENSIVE": 1,
        "PRICE_LEVEL_MODERATE": 2,
        "PRICE_LEVEL_EXPENSIVE": 3,
    }).fillna(2)
    df["price_level"] = pd.to_numeric(df["price_level"], errors="coerce").fillna(2).astype(int)
    scaler = MinMaxScaler()
    df["rating_score"] = scaler.fit_transform(df[["rating"]])
    df["popularity_score"] = scaler.fit_transform(df[["review_count"]])
    df["score"] = df["rating_score"] * 0.6 + df["popularity_score"] * 0.4
    return df.sort_values("score", ascending=False).head(top_n)

def build_email(restaurants):
    price_map = {1: "€", 2: "€€", 3: "€€€"}
    rows = ""
    for _, row in restaurants.iterrows():
        price = price_map.get(row["price_level"], "Unknown")
        website = f'<a href="{row["website"]}">Visit Website</a>' if pd.notna(row["website"]) and row["website"] != "nan" else ""
        rows += f"""
        <tr>
            <td style="padding:10px;border-bottom:1px solid #eee">
                <b>{row['name']}</b><br>
                {row['cuisine']} | ⭐ {row['rating']} | {price}<br>
                📍 {row['address']}<br>
                {website}
            </td>
        </tr>
        """
    return f"""
    <html><body>
    <h2>🍽️ Your Weekly Dublin Restaurant Picks</h2>
    <p>Here are this week's top recommendations:</p>
    <table style="width:100%;font-family:Arial">{rows}</table>
    <p style="color:gray;font-size:12px">Generated by Dublin Restaurant Recommender</p>
    </body></html>
    """

def send_email():
    restaurants = get_top_restaurants()
    html = build_email(restaurants)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "🍽️ Your Weekly Dublin Restaurant Recommendations"
    msg["From"] = GMAIL
    msg["To"] = GMAIL
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL, PASSWORD)
        server.sendmail(GMAIL, GMAIL, msg.as_string())
        print("Email sent successfully!")

if __name__ == "__main__":
    send_email()